name: build phiola

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@v4.1.0

    - name: use phiola
      run: phiola -h
      shell: bash
